### ISSUE TITLE
Create checklist dataset from supplementary material

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-macroinvertebrates#19]
Well, we thought we could just generate the checklist by grouping the occurrence data on species (42). Turns out there is much more information in the supplementary material of [Boets et al. 2016](http://www.aquaticinvasions.net/2016/AI_2016_Boets_etal.pdf)

That [Excel file](http://www.aquaticinvasions.net/2016/Supplements/AI_2016_Boets_etal_Supplement.xls) contains a sheet "Table S1", with 73 species and also:

* Phylum: empty lines with capital letters
* Order: only populated for first species of order
* Family: only populated for first species of family
* Species
* Origin: populated for all. Goes in description as "native_range"
* First occurrence in Flanders: could go in distribution as "eventDate" (at least the first date of a range)
* Pathway of introduction. Goes in description as "pathway"
* Salinity zone. Goes in description as "salinity zone"
* Reference: need to check what this is a reference for. Could go in "source"

Although we now have to source files, it still makes sense to tackle both datasets in this repository. For example, the CartoDB website should still use the output of the occurrence mapping.

**Comment by peterdesmet** [comment]
Not sure it's possible, but let's try not to edit the source Excel file at all.

**Comment by timadriaens** [comment]
A remark: the occurrences are indeed only a subset of the checklist which is normal. The checklist is also compiled of published information which can be found in the field 'reference' (so maybe this is "source"). As you can see, typically, the publication gap (time between first observation and it getting published in literature somewhere) for some species can be 10 years or more. Therefore, a good and complete checklist will have to consider both occurrences and publications. 


- [ ] habitat can be populated based on salinity zone (M = marine; F = freshwater; B = brackish (and combinations)), if species is brackish, we can assume they are estuarine based on sampling protocols described in Boets et al. 2016

- [ ] InvasionStage → consider all species "established" as they come from live samples in running waters

- [ ] although the mapping on the CBD standard may seem quite straightforward it is not, and there are some discrepancies with other registries that have mapped onto CBD (e.g. check [this](http://datadryad.org/resource/doi:10.5061/dryad.m93f6) - in fact we could use this mapping to perform ours see [Saul et al. (2016)](http://onlinelibrary.wiley.com/doi/10.1111/1365-2664.12819/full)):

- "shipping" is not a cbd standard, could either be 'Ship/boat ballast water' (for pelagic spp) or 'Ship/boat hull fouling' (for sessile organisms). 
- aquaculture = Aquaculture / mariculture (it may be that aquaculture for marine species should be "mariculture", although I doubt this is really the case for Belgium)
- corridors = Interconnected waterways/basins/seas
- aquarium trade could also be a number of things

Imo, there will clearly be a need to go back to the experts who compiled the register to do this mapping properly. In this case, it would be good to ask Pieter Boets to check the mapping.

**Comment by peterdesmet** [comment]
@timadriaens OK. Question, is it worth creating a script that completely starts from the Supplementary material (which we never ever change) or should it be more an Excel file that is based on the supplementary material (but can be updated in the future). If we opt for the latter, this is no longer a dead dataset **and** we can create a more sensible Excel layout.

**Comment by timadriaens** [comment]
I definitely favour the option of a living excelfile

**Comment by peterdesmet** [comment]
Ok! In that case it can be a csv file as well. @lienreyserhove can you make one based on the excel file? That way we don’t have to do all the cleaning actions as well. 👌

**Comment by LienReyserhove** [comment]
I updated the excel file in the folder "raw". This contains the supplementary information of [Boets et al. 2016](http://www.aquaticinvasions.net/2016/AI_2016_Boets_etal.pdf), with an extra tab named "checklist". This excel sheet will be the basis for further dwc mapping.

Below, I checked of the actions that were taken to create this checklist sheet. Unchecked actions are to be performed in R.

* [x] Ignore empty header lines: `remove_empty_rows()`
* [x] Ignore "Table S1" line: by removing that specific row number
* [ ] Use sensible column names: `clean_names()`
* [ ] Trim all cells
* [ ] Remove double spaces in cells
* [x] Transform lines with only Phylum (like ANNELIDA) to an extra column "Phylum". Not sure if there's a function for that, otherwise just hardcode in your script that lines x-y are ANNELIDA etc.
* [x] Populate Order for empty records
* [x] Populate Family for empty records
* [ ] Species looks pretty good, but we don't have authorship
* [ ] Split origin (= native_range) on `,` and `and`
* [x] Replace `Unknown` origin by `NA` => don't create records for it in description
* [ ] Recode origin so the values are similar known entities (e.g. `Southern Europe` rather than `South Europe`, use Wikipedia)
* [ ] Recode `before` and `>` dates (see alien plants)
* [ ] Split pathway on comma
* [ ] Recode pathway (see alien plants)
* [ ] Recode salinity zone to more understandable codes
* [ ] Ask if the reference can be used for every piece of information
* [ ] Recode `this study` to `Boets et al. 2016`

**Comment by LienReyserhove** [comment]
A nice overview of the mapping to DwC cheklist is given in #22, so see this issue for a detailed description
