### ISSUE TITLE
Update checklist macroinvertebrates 2024

### ISSUE THREAD

**Issue by sannegovaert** [trias-project/alien-macroinvertebrates#53]
We will release a new publication. Can you check wether the [current checklist](https://docs.google.com/spreadsheets/d/1LeXXbry2ArK2rngsmFjz_xErwE1KwQ8ujtvHNmTVA6E/edit#gid=510059691) is up to date? @timadriaens

Most important is to check:
- [ ] `degree of establishment` is `established` for all species. Is this correct? The options of this field are explained in [the Establishment vocabulary](https://rs.gbif.org/vocabulary/dwc/degree_of_establishment_2022-02-02.xml).
- [ ] update `date last observation`. In the first publication in 2016, this field was 2016 for all species. 
- [ ] add new introduced species
- [ ] The [vocabulary](https://rs.gbif.org/vocabulary/dwc/pathway_2022-02-02.xml) for `introduction pathway` has been updated. So we need to use the new terms. Please check if my suggestions are correct or need to be updated (in the spreadsheet). Here is the overview:

old pathway | new proposed pathway | alternative
-------------- | -------------- | ---------
Ship/boat hull fouling | hullFouling | 
Ship/boat ballast water | ballastWater | 
Contaminant on animals (except parasites, species transported by host/vector) | contaminantOnAnimals | 
Aquaculture | aquacultureMariculture | 
Pet/aquarium/terrarium species (including live food for such species ) | pet | liveFoodLiveBait (both can be added)
Other means of transport  | otherTransport | 
Interconnected waterways/basins/seas | waterwaysBasinsSeas | 
Mariculture | aquacultureMariculture | 

In the taxon core, there are 3 terms missing which we do have in other checklists:
- `accesssRights`: when INBO is the rightsholder, this field is https://www.inbo.be/en/norms-data-use. 
- `InstitutionCode`
- `class`: can be filled in in the spreadsheet
Do you want these fields to be added to the taxon core?
